version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../:/workspace:cached
      - try-node-node_modules:/workspace/node_modules
    command: sleep infinity
volumes:
  try-node-node_modules:
